### PR TITLE
Added Portuguese language (still working on options.dtd file)

### PR DESCRIPTION
**Pull request by smarquespt**

### CODE REVIEW

**Comment by smarquespt** [comment]
Will https://github.com/InternalError503/cyberfox/tree/master/browser/extensions/cyberctr be automatically updated or do I also need to add a pull request in there?

**Comment by InternalError503** [comment]
Hi @smarquespt Thanks so much, Yeah once your done, I will merge the pull request in to the master, Then push an update to the CyberCTR beta, Mega thanks again.

**Comment by smarquespt** [comment]
@InternalError503 
Please merge this one. The work on options.dtd will take a little more time. No need to wait for it. i'll push it when finished.

**Comment by smarquespt** [comment]
Please check also https://github.com/InternalError503/Language-Manager/pull/13

**Pull request merged**
